### ISSUE TITLE
Exceptions in class methods are not properly handled when you define an argument of any object and the user choose a wrong value

### ISSUE THREAD

**Issue by gcramarossa** [interappconnectorproject/interappconnector#6]
### ISSUE TYPE
Bug

### VERSION
0.0.9

### SHORT DESCRIPTION
When a user types a wrong value for an argument that is an object, the program raises an unhandled exception.

### DESCRIPTION
When a user types a wrong value for an argument that is an object, the program raises an unhandled exception instead of a significative error for the user.

### HOW TO REPRODUCE THE ISSUE

1. Create a console application
2. Write the following code in Program.cs
```csharp
using InterAppConnector.Interfaces;
using InterAppConnector.Attributes;

namespace InterAppConnector.App.CLI.SampleApplication
{
    public class ExampleDataModel
    {
        public Guid Guid { get; set; }
    }

    [Command("example", Description = "A command example")]
    public class ExampleCommand : ICommand<ExampleDataModel>
    {
        public string Main(ExampleDataModel arguments)
        {
            return CommandOutput.Ok(arguments.Guid.ToString());
        }
    }

    public class Program
    {
        static void Main(string[] args)
        {
            args = "example -guid 0000".Split(' ');
            CommandManager command = new CommandManager();
            command.AddCommand<ExampleCommand, ExampleDataModel>();

            InterAppCommunication connector = new InterAppCommunication(command);
            connector.ExecuteAsInteractiveCLI(args);
        }
    }
}
```
3. Build and run the project
4. The program crashes with this error
```bash
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
   at System.Guid.TryParseExactN(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at InterAppConnector.CommandManager.SetArguments(List`1 actions, List`1 argument) in D:\repos\InterAppConnector\src\InterAppConnector\CommandManager.cs:line 108
   at InterAppConnector.InterAppCommunication.ExecuteAsInteractiveCLI(String[] arguments, CommandOutputFormat commandOutputFormat) in D:\repos\InterAppConnector\src\InterAppConnector\InterAppCommunication.cs:line 82
   at InterAppConnector.App.CLI.SampleApplication.Program.Main(String[] args) in D:\repos\InterAppConnector\samples\InterAppConnector.App.CLI.SampleApplication\Program.cs:line 32
```
### ACCEPTANCE CRITERIA
The library must return a significative and user-friendly error

**Comment by gcramarossa** [comment]
The issue has been fixed.

Unit tests added in order to avoid regressions
